name: Build RPM
on: [push, pull_request]

jobs:
  rpmbuild:
      runs-on: ubuntu-latest
      container:
        image: rockylinux:8
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rpmbuild
        run: dnf -y install rpm-build

      - name: Run build script
        run: ./bdist_rpm.sh
